services:
  postgres:
    image: postgres:16
    container_name: insight_extractor_db
    environment:
      POSTGRES_USER: insight_user
      POSTGRES_PASSWORD: insight_pass
      POSTGRES_DB: insight_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
